version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/work
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret

  db:
    build:
      context: .
      dockerfile: ./db.Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_HOST: '%'
